##
## The Gremlin Configuration File
##
## Populating the values below is the preferred way to configure Gremlin installations directly on the host.
## This file is read by both `gremlin` and `gremlind` processes without having to export shell environment variables.
##
## More info at https://www.gremlin.com/docs/infrastructure-layer/advanced-configuration/
##
## Uncomment and edit the lines below to pass them to Gremlin.
## NOTE: a restart of `gremlind` is necessary to pick up changes
##

## Gremlin Identifier; uniquely identifies this agent with Gremlin
## (can also set with GREMLIN_IDENTIFIER environment variable)
#identifier: gremlin-01

## Gremlin Team Id; you can find this value at https://app.gremlin.com/settings/teams
## (can also be set with GREMLIN_TEAM_ID environment variable)
team_id: cea0b46c-9b07-4497-a0b4-6c9b075497ed

## Gremlin Client Tags; Tag your agent with key-value pairs that help you target this agent during attacks
## (can also set with GREMLIN_CLIENT_TAGS environment variable)
#tags:
#  service: pet-store
#  interface: http

## Gremlin Team Secret, should not be set when using `team_certificate`+`team_private_key`
## (can also set with GREMLIN_TEAM_SECRET environment variable)
team_secret: b1e7d2e9-289a-46eb-a7d2-e9289a36ebdd

## Gremlin Team Certificate, should not be set when using `team_secret`.
## Paste certificate content here or a paths to the file (prefixed with `file://`)
## (can also set with GREMLIN_TEAM_CERTIFICATE_OR_FILE environment variable)
team_certificate: | 
 -----BEGIN CERTIFICATE-----
  MIIBqjCCAVCgAwIBAgIBATAKBggqhkjOPQQDAjBPMSMwIQYDVQQDDBpHcmVtbGlu
  IENsaWVudCBDZXJ0aWZpY2F0ZTETMBEGA1UECwwKSG9yYSBkbyBRQTETMBEGA1UE
  CgwKSG9yYSBkbyBRQTAeFw0yNDEwMjExNzE4MzlaFw0yNTEwMjExNzE4MzlaME8x
  IzAhBgNVBAMMGkdyZW1saW4gQ2xpZW50IENlcnRpZmljYXRlMRMwEQYDVQQLDApI
  b3JhIGRvIFFBMRMwEQYDVQQKDApIb3JhIGRvIFFBMFkwEwYHKoZIzj0CAQYIKoZI
  zj0DAQcDQgAEXz5e2VGDpXDvWSska3vrNs6Ed8dFs9Zls63tvlCQZuPCRajLR4vZ
  xgIS+tPd+qjttnN5IztupfBeHSb3NXwl2aMdMBswCQYDVR0TBAIwADAOBgNVHQ8B
  Af8EBAMCB4AwCgYIKoZIzj0EAwIDSAAwRQIgfeVbBCN+B2LA/CFbuVTl+0URwkvf
  A/pJDOd9dw3RXsoCIQD1WdVSBC+iU3rXC4N72ZZD+vA/8Fkcgrj7ai9Mqpboyw==
  -----END CERTIFICATE-----
 
## Gremlin Team Certificate, should not be set when using `team_secret`.
## Paste certificate content here or a paths to the file (prefixed with `file://`)
## (can also set with GREMLIN_TEAM_PRIVATE_KEY_OR_FILE environment variable)
team_private_key: |
 -----BEGIN EC PRIVATE KEY-----
  MHcCAQEEIJRgGVKpd3j1P8tVKDRsiPxuwN7CADrUlqaZ/+aj+xKIoAoGCCqGSM49
  AwEHoUQDQgAEXz5e2VGDpXDvWSska3vrNs6Ed8dFs9Zls63tvlCQZuPCRajLR4vZ
  xgIS+tPd+qjttnN5IztupfBeHSb3NXwl2Q==
  -----END EC PRIVATE KEY-----
 
## HTTPS Proxy, set this when routing outbound Gremlin HTTPS traffic through a proxy
## (can also set with HTTPS_PROXY or https_proxy environment variables)
## https_proxy: https://localhost:3128

## SSL CERT FILE, set this when using a https proxy with a self-signed certificate
## Paste certificate content here or a paths to the file (prefixed with `file://`)
## (can also set with SSL_CERT_FILE environment variable)
#ssl_cert_file: file:///var/lib/gremlin/proxy_cert.pem

## Push Metrics, tell Gremlin whether to send system metrics to the control plane for charting the impact of attacks in
## real time. Metrics are only collected during active attacks, and only metrics relevant to the attack are collected.
## defaults to `true`
## (can also set with PUSH_METRICS environment variable)
#push_metrics: true

## Collect Process Data, data about running processes is sent to Gremlin for service discovery.
# defaults to `false`
#collect_processes: true